"""Add seats to institutes

Revision ID: 1e234c856822
Revises: 17fe8b2644f4
Create Date: 2026-03-08 23:38:43.829659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e234c856822'
down_revision: Union[str, Sequence[str], None] = '17fe8b2644f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_table('organizations')
    op.add_column('coachings', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('coachings', sa.Column('total_seats', sa.Integer(), nullable=True))
    op.add_column('coachings', sa.Column('available_seats', sa.Integer(), nullable=True))
    op.add_column('colleges', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('colleges', sa.Column('total_seats', sa.Integer(), nullable=True))
    op.add_column('colleges', sa.Column('available_seats', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('total_seats', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('available_seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'available_seats')
    op.drop_column('schools', 'total_seats')
    op.drop_column('schools', 'duration')
    op.drop_column('colleges', 'available_seats')
    op.drop_column('colleges', 'total_seats')
    op.drop_column('colleges', 'duration')
    op.drop_column('coachings', 'available_seats')
    op.drop_column('coachings', 'total_seats')
    op.drop_column('coachings', 'duration')
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('auth_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey')
    )
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###
