"""Add social handles and notifications

Revision ID: a8524662dc98
Revises: f0d6252aa5dc
Create Date: 2026-03-08 23:32:45.224203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8524662dc98'
down_revision: Union[str, Sequence[str], None] = 'f0d6252aa5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_table('organizations')
    op.add_column('users', sa.Column('social_instagram', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('social_linkedin', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('social_github', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('push_notifications', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'push_notifications')
    op.drop_column('users', 'social_github')
    op.drop_column('users', 'social_linkedin')
    op.drop_column('users', 'social_instagram')
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('auth_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey')
    )
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###
