"""Add new education profile and stay fields

Revision ID: f0d6252aa5dc
Revises: f8a1165b54de
Create Date: 2026-03-08 23:12:18.864673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d6252aa5dc'
down_revision: Union[str, Sequence[str], None] = 'f8a1165b54de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_table('organizations')
    op.add_column('coachings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('coachings', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('colleges', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('colleges', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('hostels', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('hostels', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('hostels', sa.Column('deposit', sa.Integer(), nullable=True))
    op.add_column('hostels', sa.Column('ac_available', sa.Boolean(), nullable=True))
    op.add_column('pgs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pgs', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('pgs', sa.Column('deposit', sa.Integer(), nullable=True))
    op.add_column('pgs', sa.Column('ac_available', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('blood_group', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_1', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_2', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'emergency_contact_2')
    op.drop_column('users', 'emergency_contact_1')
    op.drop_column('users', 'blood_group')
    op.drop_column('users', 'phone')
    op.drop_column('schools', 'longitude')
    op.drop_column('schools', 'latitude')
    op.drop_column('pgs', 'ac_available')
    op.drop_column('pgs', 'deposit')
    op.drop_column('pgs', 'longitude')
    op.drop_column('pgs', 'latitude')
    op.drop_column('hostels', 'ac_available')
    op.drop_column('hostels', 'deposit')
    op.drop_column('hostels', 'longitude')
    op.drop_column('hostels', 'latitude')
    op.drop_column('colleges', 'longitude')
    op.drop_column('colleges', 'latitude')
    op.drop_column('coachings', 'longitude')
    op.drop_column('coachings', 'latitude')
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('auth_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey')
    )
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###
