"""Update rating check constraint to 0-5

Revision ID: f8a1165b54de
Revises: dd5e305c31bd
Create Date: 2026-03-08 22:59:33.979149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a1165b54de'
down_revision: Union[str, Sequence[str], None] = 'dd5e305c31bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE reviews DROP CONSTRAINT IF EXISTS check_rating_range')
    op.create_check_constraint('check_rating_range', 'reviews', 'rating >= 0 AND rating <= 5')
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE reviews DROP CONSTRAINT IF EXISTS check_rating_range')
    op.create_check_constraint('check_rating_range', 'reviews', 'rating >= 1 AND rating <= 5')
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('auth_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey')
    )
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###
